alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias mkdir='mkdir -pv'

alias mktar='tar -cvf'
alias mktargz='tar -czvf'
alias mktarbz2='tar -cvjf'
alias untar='tar -xvf'
alias untarbz2='tar -xvjf'
alias untargz='tar -xvzf'

alias g='git'
alias gs='git status'
alias ga='git add'
alias gA='git add -A'
alias gc='git commit -s'
alias gcm='git commit -s -m'
alias gca='git commit --amend'
alias gpl='git pull'
alias gps='git push'
alias gb='git branch -a'
alias gck='git checkout'
alias grs='git reset'
alias gl='git log'
alias gd='git diff'
